@host = <replace with hostname>
@stage = <replace with stage>
@contentType = application/json

#########Create Product
POST https://{{host}}/{{stage}}/products
content-type: {{contentType}}

{
  "name": "new product",
  "description": "my favorite product"
}

#########Read Product
GET https://{{host}}/{{stage}}/products/100
content-type: {{contentType}}


#########Update Product
PUT https://{{host}}/{{stage}}/products/100
content-type: {{contentType}}

{
  "id": "100",
  "name": "my updated favorite product"
}

#########Delete Product
DELETE https://{{host}}/{{stage}}/products/100
content-type: {{contentType}}